name: Deploy to Amazon EKS

on:
  push:
    branches: [ "master" ]
env:
  AWS_REGION: us-east-1


permissions:
  contents: read

jobs:
  deploy:
    name: Deployment
    runs-on: self-hosted


    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecommerce01
        IMAGE_TAG: ${{ github.sha }}
    
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
    - name: Update kube config
      run: aws eks update-kubeconfig --name eks1 --region us-east-1

    - name: Deploy to EKS
      run: |
        kubectl get no
     
